name: image_clone_tool
description: A smart tool to replace value regions between two similar images.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 核心功能库
  image_picker: ^1.0.7
  google_mlkit_text_recognition: ^0.15.0
  image: ^4.1.7
  
  # 状态管理
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.4.0
  
  # 导航
  go_router: ^16.2.1
  
  # 本地持久化存储
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI & UX
  cupertino_icons: ^1.0.6
  flex_color_scheme: ^8.3.0
  
  # 工具库
  path_provider: ^2.1.2
  permission_handler: ^12.0.1
  uuid: ^4.4.0
  fuzzywuzzy: ^1.0.6
  
  # 新增：分享和保存功能
  share_plus: ^12.0.0
  gal: ^1.2.0 # 最终的、现代的、正确的替代品
  saver_gallery: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # 代码生成器
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
