# .github/workflows/release.yml

name: Release Flutter App

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本号 (例如: 1.0.0)'
        required: true
        default: '1.0.0'
      changelog:
        description: '更新日志'
        required: true
        default: '常规更新。'

jobs:
  # --- Job 1: 构建 Android APK ---
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Decode Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        run: |
          echo "storeFile=upload-keystore.jks" > android/key.properties
          echo "keyAlias=$KEY_ALIAS" >> android/key.properties
          echo "keyPassword=$KEY_PASSWORD" >> android/key.properties
          echo "storePassword=$STORE_PASSWORD" >> android/key.properties
          echo "$KEYSTORE_BASE64" | base64 --decode > android/upload-keystore.jks

      - name: Build Release APK (ARM64)
        run: flutter build apk --release --target-platform android-arm64 --split-per-abi

      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk build/app/outputs/flutter-apk/app-release-arm64.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release-arm64.apk

  # --- Job 3: 创建 Release 并上传所有产物 ---
  create-release:
    runs-on: ubuntu-latest
    needs: [build-android]
    permissions:
      contents: write # 授予 GITHUB_TOKEN 写权限以创建 Release
    steps:
      - name: Download Android APK
        uses: actions/download-artifact@v4
        with:
          name: android-apk
          path: artifacts/android


      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Release v${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.changelog }}
          files: |
            artifacts/android/app-release-arm64.apk